In [1]:
numbers = [1,2,3,4,5]
result = []
for x in numbers:
    result.append(x * 2)
print(result)

[2, 4, 6, 8, 10]


In [2]:
import numpy as np
numbers = np.array([1,2,3,4,5])
result = numbers * 2

In [3]:
result

array([ 2,  4,  6,  8, 10])

In [4]:
import numpy as np
a = np.array([10,20,30,40])
print(a.ndim)

1


In [5]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a.ndim)

2


In [6]:
a = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])
print(a.ndim)

3


In [7]:
import numpy as np
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [11]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
a

array([0., 0., 0., 0., 0.])

In [12]:
import numpy as np
a = np.array([10,20,30,40])
print(np.sum(a))

100


In [13]:
a = np.array([10,20,30,40])
print(np.average(a))

25.0


In [14]:
import numpy as np
matrix = np.eye(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
import numpy as np
values = np.linspace(0, 50, 100)
print(values)
print('number of values:', len(values))

[ 0.          0.50505051  1.01010101  1.51515152  2.02020202  2.52525253
  3.03030303  3.53535354  4.04040404  4.54545455  5.05050505  5.55555556
  6.06060606  6.56565657  7.07070707  7.57575758  8.08080808  8.58585859
  9.09090909  9.5959596  10.1010101  10.60606061 11.11111111 11.61616162
 12.12121212 12.62626263 13.13131313 13.63636364 14.14141414 14.64646465
 15.15151515 15.65656566 16.16161616 16.66666667 17.17171717 17.67676768
 18.18181818 18.68686869 19.19191919 19.6969697  20.2020202  20.70707071
 21.21212121 21.71717172 22.22222222 22.72727273 23.23232323 23.73737374
 24.24242424 24.74747475 25.25252525 25.75757576 26.26262626 26.76767677
 27.27272727 27.77777778 28.28282828 28.78787879 29.29292929 29.7979798
 30.3030303  30.80808081 31.31313131 31.81818182 32.32323232 32.82828283
 33.33333333 33.83838384 34.34343434 34.84848485 35.35353535 35.85858586
 36.36363636 36.86868687 37.37373737 37.87878788 38.38383838 38.88888889
 39.39393939 39.8989899  40.4040404  40.90909091 41.

In [26]:
import numpy as np
a = np.arange(20)
print('1D Array:')
print(a)
matrix = a.reshape(4,5)
print('2D Matrix:')
print(matrix)

1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2D Matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
import numpy as np
noise = np.random.rand(10,10)
print(noise)

[[0.27810297 0.05807021 0.79123157 0.68974236 0.38848168 0.65565796
  0.17555657 0.91159293 0.1808299  0.93796088]
 [0.14997962 0.84040236 0.7535986  0.37748196 0.44737842 0.40420842
  0.39458529 0.41618572 0.15959489 0.4573789 ]
 [0.58433448 0.77852191 0.52938967 0.26212242 0.3958119  0.43766474
  0.26224667 0.45588879 0.47222913 0.58276884]
 [0.83731506 0.81095852 0.27338964 0.22893133 0.85141761 0.81976497
  0.76246084 0.25731141 0.9965833  0.06544611]
 [0.34997528 0.05961023 0.74826702 0.55404966 0.97673074 0.81522167
  0.64478069 0.85182623 0.50087726 0.5990643 ]
 [0.92530304 0.84780434 0.0337812  0.87186486 0.85203502 0.68669482
  0.75491416 0.55546353 0.32228732 0.36685716]
 [0.47468056 0.47741677 0.45495974 0.73868327 0.79491386 0.31069242
  0.05466088 0.49224492 0.5789826  0.33990611]
 [0.42749201 0.04356259 0.40679693 0.50091019 0.29368766 0.57073014
  0.36972776 0.10804566 0.78749883 0.37745933]
 [0.62775054 0.16951756 0.54745052 0.52718765 0.5030177  0.98769129
  0.29239053

In [28]:
import numpy as np
arr = np.array([10,50,20,80,5])

In [30]:
result = arr[arr > 30]
print(result)

[50 80]


In [31]:
import numpy as np
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

In [32]:
middle = arr[:,1]
print(middle)

[20 50 80]
